#+TITLE: Emacs configuration
#+AUTHOR: Michael Zapata
#+EMAIL: michael.zapata@protonmail.com

* Basic configuration

** Keep the starting screen clean

Once you've gone through the tutorial, there's no real need to keep the startup
layout.

#+BEGIN_SRC emacs-lisp
(setq inhibit-splash-screen t
      inhibit-startup-message t
      inhibit-startup-echo-area-message t)
#+END_SRC

** Keep the GUI minimalistic

As I want my editor to get as much screen estate as possible, and prefer
keyboard-driven workflows, remove every visible bar, keeping only the mode-line.

#+BEGIN_SRC emacs-lisp
(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
#+END_SRC

** Package management

*** Use a package manager

As a vim user, I am used to have a package manager taking care of things for me.
[[https://github.com/jwiegley/use-package][=use-package=]] is the most advanced
one, allowing lazy-loading and fine-grained control that is not found by default
in emacs.

#+BEGIN_SRC emacs-lisp
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(setq use-package-verbose t)
(setq use-package-always-ensure t)

(eval-when-compile (require 'use-package))
#+END_SRC

* Vim experience

Disclaimer: I am a vim user at heart. I will try to emulate all the good parts.

** Install it

Evil mode is the emacs plugin that is allowing me to switch from vim to emacs.
It provides a complete modal interface in line with the vanilla vim
experience, which is the main thing I cannot edit without.

#+BEGIN_SRC emacs-lisp
(use-package evil
  :init
  (evil-mode 1))
#+END_SRC

** Install =evil-surround=

It's one of the most interesting edition plugin available for vim, no
reason not to use it here.

#+BEGIN_SRC emacs-lisp
(use-package evil-surround
  :after evil
  :init
  (global-evil-surround-mode 1))
#+END_SRC
